CREATE DATABASE TrainingCourses
ON
(
	NAME = 'TrainingCourses',
	FILENAME = 'D:\TrainingCourses.mdf',
	SIZE = 10MB,
	MAXSIZE = 20MB,
	FILEGROWTH = 5MB
)
LOG ON
(
	NAME = 'LogTrainingCourses',
	FILENAME = 'D:\TrainingCourses.ldf',
	SIZE = 5MB,
	MAXSIZE = 10MB,
	FILEGROWTH = 5MB
)               
COLLATE Latin1_General_CI_AS
GO

USE TrainingCourses
GO

CREATE TABLE COURSES
(
	COURSE_ID int IDENTITY NOT NULL PRIMARY KEY,
	NAME varchar(50) NOT NULL,
	DESCRIPTION  Varchar(500) NOT NULL,
)
GO

CREATE TABLE GROUPS
(
	GROUP_ID int IDENTITY NOT NULL PRIMARY KEY,
	NAME varchar(10) NOT NULL,
	--COURSE_ID int NOT NULL FOREIGN KEY REFERENCES COURSES(COURSE_ID), how to add COURSE_ID, with unique GROUP_ID and NAME???
)
GO

CREATE TABLE GROUPS_COURSES
(
	GROUP_ID int NOT NULL FOREIGN KEY REFERENCES GROUPS(GROUP_ID),
	COURSE_ID int NOT NULL FOREIGN KEY REFERENCES COURSES(COURSE_ID),
	PRIMARY KEY(GROUP_ID, COURSE_ID)
)

GO
CREATE TABLE STUDENTS
(
	STUDENT_ID int IDENTITY NOT NULL PRIMARY KEY,
	GROUP_ID int NOT NULL FOREIGN KEY REFERENCES GROUPS(GROUP_ID),
	FIRST_NAME varchar(20) NOT NULL,
	LAST_NAME varchar(20) NULL,
)
GO


--DROP TABLE STUDENTS
--DROP TABLE GROUPS
--DROP TABLE COURSES
--DROP TABLE GROUPS_COURSES
--DROP DATABASE TrainingCourses