USE TrainingCourses
GO

SELECT c.NAME, s.FIRST_NAME + ' ' + s.LAST_NAME AS Student
FROM GROUPS AS g
JOIN COURSES AS c ON c.COURSE_ID = g.COURSE_ID
JOIN STUDENTS AS s ON g.GROUP_ID = s.GROUP_ID
ORDER BY c.NAME