USE TrainingCourses
GO

SELECT COUNT(STUDENT_ID) AS SR_01_Students_Count
FROM STUDENTS AS s
JOIN GROUPS AS g ON s.GROUP_ID = g.GROUP_ID
WHERE NAME = 'SR-01'
GO

DELETE FROM STUDENTS
WHERE STUDENT_ID IN (
 SELECT STUDENT_ID
 FROM STUDENTS AS s
 JOIN GROUPS AS g ON s.GROUP_ID = g.GROUP_ID
 WHERE NAME = 'SR-01'
 )
GO

SELECT COUNT(STUDENT_ID) AS SR_01_Students_Count
FROM STUDENTS AS s
JOIN GROUPS AS g ON s.GROUP_ID = g.GROUP_ID
WHERE NAME = 'SR-01'